name: Build CI image

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Read firefox version
        id: version
        run: echo "version=$(jq -r .version.version firefox.json)" >> "$GITHUB_OUTPUT"

      - name: Build & push CI image
        uses: ./.github/actions/build-ci-image
        with:
          image-tag: ${{ steps.version.outputs.version }}
