import fs from "fs/promises";
import { fileURLToPath } from "url";
import config from "../firefox.json" with { type: "json" };
import { dedent } from "../src/glide/browser/base/content/utils/dedent.mts";
import { $ } from "./zx.mts";

$.set_root_dir();

const BUNDLED_FILE = "src/glide/browser/base/content/dist/bundled.compiled.d.ts";
const HEADER = dedent`
/* ======================================================
                Glide version: ${config.brands.glide.release.displayVersion}
   ====================================================== */
`;

export async function bundle_types() {
  await $`./node_modules/.bin/dts-bundle-generator \
    src/glide/browser/base/content/bundled.d.ts \
    -o ${BUNDLED_FILE} \
    --inline-declare-global \
    --project tsconfig.bundled.json`;

  let content = await fs.readFile(BUNDLED_FILE, "utf-8");
  content = content.replace(/Generated by dts-bundle-generator .*/g, "");

  await fs.writeFile(BUNDLED_FILE, HEADER + "\n" + content);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await bundle_types();
}
