#!/usr/bin/env bash

set -eux

cd "$(dirname "$0")/.."

TEMP_FILE=$(mktemp)
BUNDLED_FILE="src/glide/browser/base/content/dist/bundled.compiled.d.ts"

pnpm dts-bundle-generator \
  src/glide/browser/base/content/bundled.d.ts \
  -o "$BUNDLED_FILE" \
  --inline-declare-global \
  --project tsconfig.bundled.json

{
    cat <<EOF
/* ======================================================
                Glide version: $(pnpm --silent tsn scripts/version.mts)
   ====================================================== */
EOF
  sed '/Generated by dts-bundle-generator .*/d' "$BUNDLED_FILE"
} > "$TEMP_FILE" && mv "$TEMP_FILE" "$BUNDLED_FILE"
