name: Linux Build

on:
  workflow_dispatch:
    inputs:
      upload:
        description: "Upload built artifacts"
        type: boolean
        default: true
      MOZ_BUILD_DATE:
        type: string
        default: ""
        description: "Set the build id"
  workflow_call:
    inputs:
      upload:
        description: "Used to distinguish dispatch and call events"
        required: true
        type: boolean
      MOZ_BUILD_DATE:
        type: string
        default: ""
        description: "Set the build id"

jobs:
  linux-build:
    name: Build - ${{ matrix.arch }}

    runs-on: ${{ matrix.arch == 'x86_64' && 'depot-ubuntu-24.04-16' || 'depot-ubuntu-24.04-arm-16' }}
    env:
      CARGO_TERM_COLOR: always
      GLIDE_PLATFORM: linux
      GLIDE_RELEASE: true
      GLIDE_DISABLE_PGO: 1
      GLIDE_COMPAT: ${{ matrix.arch }}
      MOZ_BUILD_DATE: ${{ inputs.MOZ_BUILD_DATE }}

    defaults:
      run:
        shell: nix develop --command bash -e {0}

    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, x86_64]

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-nix

      - name: Configure git
        run: |
          git config --global \
            url."https://github.com/mozilla-firefox/firefox.git".insteadOf \
            "git@github.com:mozilla-firefox/firefox.git"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
        with:
          disable_annotations: true

      - name: Expose actions cache variables
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bootstrap repo
        run: |
          pnpm bootstrap

          cd engine
          ./mach --no-interactive bootstrap --application-choice browser --no-system-changes || true
          cd ..

      - name: Configure rust
        run: |
          if test "$GLIDE_COMPAT" = "aarch64"; then
            rustup target add aarch64-unknown-linux-gnu
          else
            rustup target add x86_64-unknown-linux-gnu
          fi

      - name: Build
        run: |
          pnpm build

      - name: Package
        run: |
          pnpm package

      - name: Rename artifacts
        run: |
          mv dist/glide-*.tar.xz "dist/glide.linux-$GLIDE_COMPAT.tar.xz"

      - name: Upload tar
        if: inputs.upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          retention-days: 10
          name: glide.linux-${{ matrix.arch }}.tar.xz
          path: ./dist/glide.linux-${{ matrix.arch }}.tar.xz
