name: Post release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write # we're pushing a branch

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          persist-credentials: true

      # will trigger another deploy
      - name: Reset docs branch
        run: |
          git fetch
          git checkout -b docs-production origin/docs-production
          git reset --hard origin/main
          git push --force-with-lease
