name: Release

on:
  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # needed while we have private dependencies
      - name: Configure GitHub auth
        run: |
          TOKEN="${{ secrets.REPO_ACCESS_TOKEN }}"

          git config --global \
            url."https://x-access-token:${TOKEN}@github.com/glide-browser/glider.git".insteadOf \
            "git@github.com:glide-browser/glider.git"

          git config --global \
            url."https://x-access-token:${TOKEN}@github.com/glide-browser/webextension-types.git".insteadOf \
            "git@github.com:glide-browser/webextension-types.git"

          git config --global \
            url."https://github.com/mozilla-firefox/firefox.git".insteadOf \
            "git@github.com:mozilla-firefox/firefox.git"

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Glider config
        run: pnpm glider set brand glide

      - name: Get version
        id: version
        run: |
          echo "version=$(pnpm glider get version)" >> $GITHUB_OUTPUT

      - name: Create draft release
        run: |
          if gh release view $VERSION > /dev/null 2>&1; then
            gh release edit $VERSION --prerelease --draft --title "$VERSION" --target "${{ github.sha }}"
          else
            gh release create $VERSION --prerelease --draft --title "$VERSION" --target "${{ github.sha }}"
          fi
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}

  linux:
    name: Linux build
    uses: ./.github/workflows/linux-build.yml
    secrets: inherit
    with:
      upload: true

  macos:
    name: macOS build
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
    with:
      artifacts: true

  macos-sign:
    name: macOS sign
    needs: [macos]
    uses: ./.github/workflows/macos-sign.yml
    secrets: inherit
    with:
      artifacts: true

  source:
    runs-on: ubuntu-latest
    needs: [metadata]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # needed while we have private dependencies
      - name: Configure GitHub auth
        run: |
          TOKEN="${{ secrets.REPO_ACCESS_TOKEN }}"

          git config --global \
            url."https://x-access-token:${TOKEN}@github.com/glide-browser/glider.git".insteadOf \
            "git@github.com:glide-browser/glider.git"

          git config --global \
            url."https://x-access-token:${TOKEN}@github.com/glide-browser/webextension-types.git".insteadOf \
            "git@github.com:glide-browser/webextension-types.git"

          git config --global \
            url."https://github.com/mozilla-firefox/firefox.git".insteadOf \
            "git@github.com:mozilla-firefox/firefox.git"

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bootstrap repo
        run: |
          pnpm bootstrap

      - name: Compress
        working-directory: engine
        run: |
          tar --use-compress-program=zstd -hcf ../glide.source.tar.zst *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          name: glide.source.tar.zst
          path: ./glide.source.tar.zst

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [metadata, linux, macos, macos-sign, source]
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Linux build (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: glide.linux-aarch64.tar.xz

      - name: Download Linux build (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: glide.linux-x86_64.tar.xz

      - name: Download linux MAR (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: linux-aarch64.mar

      - name: Download linux MAR (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64.mar

      - name: Download signed macOS DMG (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: glide.macos-aarch64.signed.dmg

      - name: Download signed macOS DMG (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: glide.macos-x86_64.signed.dmg

      - name: Download macOS MAR (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64.mar

      - name: Download macOS MAR (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: macos-x86_64.mar

      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: glide.source.tar.zst

      - name: Upload artifacts to the release
        run: |
          gh release upload $VERSION ./glide.linux-aarch64.tar.xz --clobber
          gh release upload $VERSION ./glide.linux-x86_64.tar.xz --clobber
          gh release upload $VERSION ./glide.macos-aarch64.dmg --clobber
          gh release upload $VERSION ./glide.macos-x86_64.dmg --clobber
          gh release upload $VERSION ./glide.source.tar.zst --clobber

          # MAR files
          gh release upload $VERSION ./linux-aarch64.mar --clobber
          gh release upload $VERSION ./linux-x86_64.mar --clobber
          gh release upload $VERSION ./macos-aarch64.mar --clobber
          gh release upload $VERSION ./macos-x86_64.mar --clobber
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          VERSION: ${{ needs.metadata.outputs.version }}

  push-update-manifests:
    name: Push update manifests
    runs-on: ubuntu-latest
    needs: [release, metadata]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # we explicitly do want to persist credentials because we push changes
      - name: Checkout update-server repository
        uses: actions/checkout@v4  # zizmor: ignore[artipacked]
        with:
          repository: glide-browser/update-server
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: update-server
          ref: main

      - name: Download Linux updates (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: linux-aarch64-updates
          path: artifacts/linux-aarch64/

      - name: Download Linux updates (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64-updates
          path: artifacts/linux-x86_64/

      - name: Download macOS updates (aarch64)
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64-updates
          path: artifacts/macos-aarch64/

      - name: Download macOS updates (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: macos-x86_64-updates
          path: artifacts/macos-x86_64/

      - name: Debug
        run: |
          tree -Dh artifacts/

      # temporary while the repo is private
      - name: Fix update.xml URLs
        run: |
          .github/scripts/fix-update-urls.sh artifacts/
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy update files to update-server
        run: |
          mkdir -p update-server/public/updates/
          cp -r artifacts/linux-aarch64/* update-server/public/versions/latest/
          cp -r artifacts/linux-x86_64/* update-server/public/versions/latest/
          cp -r artifacts/macos-aarch64/* update-server/public/versions/latest/
          cp -r artifacts/macos-x86_64/* update-server/public/versions/latest/

      - name: Debug
        run: |
          tree -Dh update-server/public/

      - name: Commit and push updates
        working-directory: update-server
        run: |
          git config user.name "glide-updater"
          git config user.email "updates@glide-browser.app"

          git add -A .

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add update files for version ${VERSION}"
            git push
          fi
        env:
          VERSION: "${{ needs.metadata.outputs.version }}"
